// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: header.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 指定服务转发
type NodeRpcInfo struct {
	state         protoimpl.MessageState  `gorm:"-"`
	sizeCache     protoimpl.SizeCache     `gorm:"-"`
	unknownFields protoimpl.UnknownFields `gorm:"-"`

	ServiceName string `protobuf:"bytes,1,opt,name=serviceName,proto3" json:"serviceName,omitempty"` //服务名
	NodeName    string `protobuf:"bytes,2,opt,name=nodeName,proto3" json:"nodeName,omitempty"`
}

func (x *NodeRpcInfo) Reset() {
	*x = NodeRpcInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_header_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeRpcInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRpcInfo) ProtoMessage() {}

func (x *NodeRpcInfo) ProtoReflect() protoreflect.Message {
	mi := &file_header_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRpcInfo.ProtoReflect.Descriptor instead.
func (*NodeRpcInfo) Descriptor() ([]byte, []int) {
	return file_header_proto_rawDescGZIP(), []int{0}
}

func (x *NodeRpcInfo) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *NodeRpcInfo) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

type Context struct {
	state         protoimpl.MessageState  `gorm:"-"`
	sizeCache     protoimpl.SizeCache     `gorm:"-"`
	unknownFields protoimpl.UnknownFields `gorm:"-"`

	GateName string            `protobuf:"bytes,1,opt,name=gateName,proto3" json:"gateName,omitempty"` //客户端连接网关名
	Remote   string            `protobuf:"bytes,2,opt,name=remote,proto3" json:"remote,omitempty"`     //客户端连接地址
	Id       uint64            `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`            //连接id
	Token    string            `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`       //
	Uid      uint64            `protobuf:"varint,5,opt,name=uid,proto3" json:"uid,omitempty"`          //玩家id
	Nodes    []*NodeRpcInfo    `protobuf:"bytes,6,rep,name=nodes,proto3" json:"nodes,omitempty"`
	CallId   uint64            `protobuf:"varint,7,opt,name=callId,proto3" json:"callId,omitempty"` //本次调用id
	Game     string            `protobuf:"bytes,8,opt,name=game,proto3" json:"game,omitempty"`
	Kvs      map[string]string `protobuf:"bytes,9,rep,name=kvs,proto3" json:"kvs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Ps       map[string]int64  `protobuf:"bytes,10,rep,name=ps,proto3" json:"ps,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *Context) Reset() {
	*x = Context{}
	if protoimpl.UnsafeEnabled {
		mi := &file_header_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Context) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Context) ProtoMessage() {}

func (x *Context) ProtoReflect() protoreflect.Message {
	mi := &file_header_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Context.ProtoReflect.Descriptor instead.
func (*Context) Descriptor() ([]byte, []int) {
	return file_header_proto_rawDescGZIP(), []int{1}
}

func (x *Context) GetGateName() string {
	if x != nil {
		return x.GateName
	}
	return ""
}

func (x *Context) GetRemote() string {
	if x != nil {
		return x.Remote
	}
	return ""
}

func (x *Context) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Context) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Context) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Context) GetNodes() []*NodeRpcInfo {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *Context) GetCallId() uint64 {
	if x != nil {
		return x.CallId
	}
	return 0
}

func (x *Context) GetGame() string {
	if x != nil {
		return x.Game
	}
	return ""
}

func (x *Context) GetKvs() map[string]string {
	if x != nil {
		return x.Kvs
	}
	return nil
}

func (x *Context) GetPs() map[string]int64 {
	if x != nil {
		return x.Ps
	}
	return nil
}

type ReqHeader struct {
	state         protoimpl.MessageState  `gorm:"-"`
	sizeCache     protoimpl.SizeCache     `gorm:"-"`
	unknownFields protoimpl.UnknownFields `gorm:"-"`

	Method  string   `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Seq     uint64   `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Context *Context `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	NoResp  bool     `protobuf:"varint,4,opt,name=noResp,proto3" json:"noResp,omitempty"`
	Raw     int32    `protobuf:"varint,5,opt,name=raw,proto3" json:"raw,omitempty"`
}

func (x *ReqHeader) Reset() {
	*x = ReqHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_header_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqHeader) ProtoMessage() {}

func (x *ReqHeader) ProtoReflect() protoreflect.Message {
	mi := &file_header_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqHeader.ProtoReflect.Descriptor instead.
func (*ReqHeader) Descriptor() ([]byte, []int) {
	return file_header_proto_rawDescGZIP(), []int{2}
}

func (x *ReqHeader) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ReqHeader) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *ReqHeader) GetContext() *Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ReqHeader) GetNoResp() bool {
	if x != nil {
		return x.NoResp
	}
	return false
}

func (x *ReqHeader) GetRaw() int32 {
	if x != nil {
		return x.Raw
	}
	return 0
}

type RspHeader struct {
	state         protoimpl.MessageState  `gorm:"-"`
	sizeCache     protoimpl.SizeCache     `gorm:"-"`
	unknownFields protoimpl.UnknownFields `gorm:"-"`

	Method  string   `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Seq     uint64   `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Error   string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Ret     uint32   `protobuf:"varint,4,opt,name=ret,proto3" json:"ret,omitempty"`
	Context *Context `protobuf:"bytes,5,opt,name=context,proto3" json:"context,omitempty"`
	NoResp  bool     `protobuf:"varint,6,opt,name=noResp,proto3" json:"noResp,omitempty"`
	Raw     int32    `protobuf:"varint,7,opt,name=raw,proto3" json:"raw,omitempty"`
}

func (x *RspHeader) Reset() {
	*x = RspHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_header_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspHeader) ProtoMessage() {}

func (x *RspHeader) ProtoReflect() protoreflect.Message {
	mi := &file_header_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspHeader.ProtoReflect.Descriptor instead.
func (*RspHeader) Descriptor() ([]byte, []int) {
	return file_header_proto_rawDescGZIP(), []int{3}
}

func (x *RspHeader) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RspHeader) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *RspHeader) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RspHeader) GetRet() uint32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *RspHeader) GetContext() *Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *RspHeader) GetNoResp() bool {
	if x != nil {
		return x.NoResp
	}
	return false
}

func (x *RspHeader) GetRaw() int32 {
	if x != nil {
		return x.Raw
	}
	return 0
}

type NullMessage struct {
	state         protoimpl.MessageState  `gorm:"-"`
	sizeCache     protoimpl.SizeCache     `gorm:"-"`
	unknownFields protoimpl.UnknownFields `gorm:"-"`
}

func (x *NullMessage) Reset() {
	*x = NullMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_header_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NullMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullMessage) ProtoMessage() {}

func (x *NullMessage) ProtoReflect() protoreflect.Message {
	mi := &file_header_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullMessage.ProtoReflect.Descriptor instead.
func (*NullMessage) Descriptor() ([]byte, []int) {
	return file_header_proto_rawDescGZIP(), []int{4}
}

var File_header_proto protoreflect.FileDescriptor

var file_header_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4b,
	0x0a, 0x0b, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x70, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x20, 0x0a,
	0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0xfb, 0x02, 0x0a, 0x07,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x61, 0x74, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x61, 0x74, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03,
	0x75, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x06, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x70, 0x63, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x61, 0x6c, 0x6c, 0x49,
	0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x63, 0x61, 0x6c, 0x6c, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x67,
	0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x03, 0x6b, 0x76, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x2e, 0x4b, 0x76, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x03, 0x6b, 0x76, 0x73, 0x12, 0x20, 0x0a, 0x02, 0x70, 0x73, 0x18, 0x0a,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x2e, 0x50,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x02, 0x70, 0x73, 0x1a, 0x36, 0x0a, 0x08, 0x4b, 0x76,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02,
	0x38, 0x01, 0x1a, 0x35, 0x0a, 0x07, 0x50, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x83, 0x01, 0x0a, 0x09, 0x52, 0x65,
	0x71, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x73, 0x65,
	0x71, 0x12, 0x22, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x08, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x52, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x6e, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a,
	0x03, 0x72, 0x61, 0x77, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x72, 0x61, 0x77, 0x22,
	0xab, 0x01, 0x0a, 0x09, 0x52, 0x73, 0x70, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x16, 0x0a,
	0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x03, 0x73, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x10, 0x0a,
	0x03, 0x72, 0x65, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12,
	0x22, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x08, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x78, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x06, 0x6e, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x72,
	0x61, 0x77, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x72, 0x61, 0x77, 0x22, 0x0d, 0x0a,
	0x0b, 0x4e, 0x75, 0x6c, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x08, 0x5a, 0x06,
	0x2e, 0x2f, 0x3b, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_header_proto_rawDescOnce sync.Once
	file_header_proto_rawDescData = file_header_proto_rawDesc
)

func file_header_proto_rawDescGZIP() []byte {
	file_header_proto_rawDescOnce.Do(func() {
		file_header_proto_rawDescData = protoimpl.X.CompressGZIP(file_header_proto_rawDescData)
	})
	return file_header_proto_rawDescData
}

var file_header_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_header_proto_goTypes = []interface{}{
	(*NodeRpcInfo)(nil), // 0: NodeRpcInfo
	(*Context)(nil),     // 1: Context
	(*ReqHeader)(nil),   // 2: ReqHeader
	(*RspHeader)(nil),   // 3: RspHeader
	(*NullMessage)(nil), // 4: NullMessage
	nil,                 // 5: Context.KvsEntry
	nil,                 // 6: Context.PsEntry
}
var file_header_proto_depIdxs = []int32{
	0, // 0: Context.nodes:type_name -> NodeRpcInfo
	5, // 1: Context.kvs:type_name -> Context.KvsEntry
	6, // 2: Context.ps:type_name -> Context.PsEntry
	1, // 3: ReqHeader.context:type_name -> Context
	1, // 4: RspHeader.context:type_name -> Context
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_header_proto_init() }
func file_header_proto_init() {
	if File_header_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_header_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeRpcInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_header_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Context); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_header_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_header_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_header_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NullMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_header_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_header_proto_goTypes,
		DependencyIndexes: file_header_proto_depIdxs,
		MessageInfos:      file_header_proto_msgTypes,
	}.Build()
	File_header_proto = out.File
	file_header_proto_rawDesc = nil
	file_header_proto_goTypes = nil
	file_header_proto_depIdxs = nil
}
