// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v4.23.4
// source: examples/rpc/message.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddReq struct {
	state         protoimpl.MessageState  `gorm:"-"`
	sizeCache     protoimpl.SizeCache     `gorm:"-"`
	unknownFields protoimpl.UnknownFields `gorm:"-"`

	A uint64 `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B uint64 `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
}

func (x *AddReq) Reset() {
	*x = AddReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_examples_rpc_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReq) ProtoMessage() {}

func (x *AddReq) ProtoReflect() protoreflect.Message {
	mi := &file_examples_rpc_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReq.ProtoReflect.Descriptor instead.
func (*AddReq) Descriptor() ([]byte, []int) {
	return file_examples_rpc_message_proto_rawDescGZIP(), []int{0}
}

func (x *AddReq) GetA() uint64 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *AddReq) GetB() uint64 {
	if x != nil {
		return x.B
	}
	return 0
}

type AddRsp struct {
	state         protoimpl.MessageState  `gorm:"-"`
	sizeCache     protoimpl.SizeCache     `gorm:"-"`
	unknownFields protoimpl.UnknownFields `gorm:"-"`

	C uint64 `protobuf:"varint,1,opt,name=c,proto3" json:"c,omitempty"`
}

func (x *AddRsp) Reset() {
	*x = AddRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_examples_rpc_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRsp) ProtoMessage() {}

func (x *AddRsp) ProtoReflect() protoreflect.Message {
	mi := &file_examples_rpc_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRsp.ProtoReflect.Descriptor instead.
func (*AddRsp) Descriptor() ([]byte, []int) {
	return file_examples_rpc_message_proto_rawDescGZIP(), []int{1}
}

func (x *AddRsp) GetC() uint64 {
	if x != nil {
		return x.C
	}
	return 0
}

var File_examples_rpc_message_proto protoreflect.FileDescriptor

var file_examples_rpc_message_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61,
	0x69, 0x6e, 0x22, 0x24, 0x0a, 0x06, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x12, 0x0c, 0x0a, 0x01,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x01, 0x61, 0x12, 0x0c, 0x0a, 0x01, 0x62, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x01, 0x62, 0x22, 0x16, 0x0a, 0x06, 0x41, 0x64, 0x64, 0x52,
	0x73, 0x70, 0x12, 0x0c, 0x0a, 0x01, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x01, 0x63,
	0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73,
	0x65, 0x76, 0x65, 0x79, 0x65, 0x2f, 0x67, 0x6f, 0x6d, 0x73, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x73, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x6d, 0x61, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_examples_rpc_message_proto_rawDescOnce sync.Once
	file_examples_rpc_message_proto_rawDescData = file_examples_rpc_message_proto_rawDesc
)

func file_examples_rpc_message_proto_rawDescGZIP() []byte {
	file_examples_rpc_message_proto_rawDescOnce.Do(func() {
		file_examples_rpc_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_examples_rpc_message_proto_rawDescData)
	})
	return file_examples_rpc_message_proto_rawDescData
}

var file_examples_rpc_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_examples_rpc_message_proto_goTypes = []interface{}{
	(*AddReq)(nil), // 0: main.AddReq
	(*AddRsp)(nil), // 1: main.AddRsp
}
var file_examples_rpc_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_examples_rpc_message_proto_init() }
func file_examples_rpc_message_proto_init() {
	if File_examples_rpc_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_examples_rpc_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_examples_rpc_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_examples_rpc_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_examples_rpc_message_proto_goTypes,
		DependencyIndexes: file_examples_rpc_message_proto_depIdxs,
		MessageInfos:      file_examples_rpc_message_proto_msgTypes,
	}.Build()
	File_examples_rpc_message_proto = out.File
	file_examples_rpc_message_proto_rawDesc = nil
	file_examples_rpc_message_proto_goTypes = nil
	file_examples_rpc_message_proto_depIdxs = nil
}
