// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type QueryReq struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryReq) Reset()         { *m = QueryReq{} }
func (m *QueryReq) String() string { return proto.CompactTextString(m) }
func (*QueryReq) ProtoMessage()    {}
func (*QueryReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *QueryReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryReq.Unmarshal(m, b)
}
func (m *QueryReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryReq.Marshal(b, m, deterministic)
}
func (m *QueryReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryReq.Merge(m, src)
}
func (m *QueryReq) XXX_Size() int {
	return xxx_messageInfo_QueryReq.Size(m)
}
func (m *QueryReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryReq.DiscardUnknown(m)
}

var xxx_messageInfo_QueryReq proto.InternalMessageInfo

func (m *QueryReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type QueryRsp struct {
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryRsp) Reset()         { *m = QueryRsp{} }
func (m *QueryRsp) String() string { return proto.CompactTextString(m) }
func (*QueryRsp) ProtoMessage()    {}
func (*QueryRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *QueryRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRsp.Unmarshal(m, b)
}
func (m *QueryRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRsp.Marshal(b, m, deterministic)
}
func (m *QueryRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRsp.Merge(m, src)
}
func (m *QueryRsp) XXX_Size() int {
	return xxx_messageInfo_QueryRsp.Size(m)
}
func (m *QueryRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRsp.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRsp proto.InternalMessageInfo

func (m *QueryRsp) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type UpdateReq struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateReq) Reset()         { *m = UpdateReq{} }
func (m *UpdateReq) String() string { return proto.CompactTextString(m) }
func (*UpdateReq) ProtoMessage()    {}
func (*UpdateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *UpdateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateReq.Unmarshal(m, b)
}
func (m *UpdateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateReq.Marshal(b, m, deterministic)
}
func (m *UpdateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateReq.Merge(m, src)
}
func (m *UpdateReq) XXX_Size() int {
	return xxx_messageInfo_UpdateReq.Size(m)
}
func (m *UpdateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateReq proto.InternalMessageInfo

func (m *UpdateReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *UpdateReq) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type UpdateRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRsp) Reset()         { *m = UpdateRsp{} }
func (m *UpdateRsp) String() string { return proto.CompactTextString(m) }
func (*UpdateRsp) ProtoMessage()    {}
func (*UpdateRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *UpdateRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRsp.Unmarshal(m, b)
}
func (m *UpdateRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRsp.Marshal(b, m, deterministic)
}
func (m *UpdateRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRsp.Merge(m, src)
}
func (m *UpdateRsp) XXX_Size() int {
	return xxx_messageInfo_UpdateRsp.Size(m)
}
func (m *UpdateRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRsp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRsp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*QueryReq)(nil), "pb.QueryReq")
	proto.RegisterType((*QueryRsp)(nil), "pb.QueryRsp")
	proto.RegisterType((*UpdateReq)(nil), "pb.UpdateReq")
	proto.RegisterType((*UpdateRsp)(nil), "pb.UpdateRsp")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 116 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x92, 0xe1,
	0xe2, 0x08, 0x2c, 0x4d, 0x2d, 0xaa, 0x0c, 0x4a, 0x2d, 0x14, 0x12, 0xe0, 0x62, 0xce, 0x4e, 0xad,
	0x94, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0x31, 0x95, 0x14, 0x60, 0xb2, 0xc5, 0x05, 0x42,
	0x22, 0x5c, 0xac, 0x65, 0x89, 0x39, 0xa5, 0xa9, 0x12, 0x4c, 0x60, 0x79, 0x08, 0x47, 0xc9, 0x98,
	0x8b, 0x33, 0xb4, 0x20, 0x25, 0xb1, 0x24, 0x15, 0xab, 0x01, 0x38, 0x34, 0x71, 0xc3, 0x35, 0x15,
	0x17, 0x24, 0xb1, 0x81, 0x1d, 0x63, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x13, 0x7d, 0x4b, 0xfc,
	0x9d, 0x00, 0x00, 0x00,
}
